[package]
name = "OOMGuardAllocator"
version = "0.1.0"
edition = "2021"
build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"
rand = "0.3.17"
libm = "0.2.2"

lazy_static = "1.4.0"


[profile.dev]
lto = true